version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
